package edu.utep.cybershare.rim.ontology;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Agency <br>
 * @version generated on Wed Jun 11 10:09:29 GMT-07:00 2014 by nick
 */

public interface Agency extends WrappedIndividual {

    /* ***************************************************
     * Property http://ontology.cybershare.utep.edu/RIM/rim.owl#fundsProject
     */
     
    /**
     * Gets all property values for the fundsProject property.<p>
     * 
     * @returns a collection of values for the fundsProject property.
     */
    Collection<? extends Project> getFundsProject();

    /**
     * Checks if the class has a fundsProject property value.<p>
     * 
     * @return true if there is a fundsProject property value.
     */
    boolean hasFundsProject();

    /**
     * Adds a fundsProject property value.<p>
     * 
     * @param newFundsProject the fundsProject property value to be added
     */
    void addFundsProject(Project newFundsProject);

    /**
     * Removes a fundsProject property value.<p>
     * 
     * @param oldFundsProject the fundsProject property value to be removed.
     */
    void removeFundsProject(Project oldFundsProject);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
