package edu.utep.cybershare.rim.ontology;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Person <br>
 * @version generated on Wed Jun 11 10:09:29 GMT-07:00 2014 by nick
 */

public interface Person extends WrappedIndividual {

    /* ***************************************************
     * Property http://ontology.cybershare.utep.edu/RIM/rim.owl#affiliatedWithInstitution
     */
     
    /**
     * Gets all property values for the affiliatedWithInstitution property.<p>
     * 
     * @returns a collection of values for the affiliatedWithInstitution property.
     */
    Collection<? extends Institution> getAffiliatedWithInstitution();

    /**
     * Checks if the class has a affiliatedWithInstitution property value.<p>
     * 
     * @return true if there is a affiliatedWithInstitution property value.
     */
    boolean hasAffiliatedWithInstitution();

    /**
     * Adds a affiliatedWithInstitution property value.<p>
     * 
     * @param newAffiliatedWithInstitution the affiliatedWithInstitution property value to be added
     */
    void addAffiliatedWithInstitution(Institution newAffiliatedWithInstitution);

    /**
     * Removes a affiliatedWithInstitution property value.<p>
     * 
     * @param oldAffiliatedWithInstitution the affiliatedWithInstitution property value to be removed.
     */
    void removeAffiliatedWithInstitution(Institution oldAffiliatedWithInstitution);


    /* ***************************************************
     * Property http://ontology.cybershare.utep.edu/RIM/rim.owl#hasEmailSHA1Sum
     */
     
    /**
     * Gets all property values for the hasEmailSHA1Sum property.<p>
     * 
     * @returns a collection of values for the hasEmailSHA1Sum property.
     */
    Collection<? extends String> getHasEmailSHA1Sum();

    /**
     * Checks if the class has a hasEmailSHA1Sum property value.<p>
     * 
     * @return true if there is a hasEmailSHA1Sum property value.
     */
    boolean hasHasEmailSHA1Sum();

    /**
     * Adds a hasEmailSHA1Sum property value.<p>
     * 
     * @param newHasEmailSHA1Sum the hasEmailSHA1Sum property value to be added
     */
    void addHasEmailSHA1Sum(String newHasEmailSHA1Sum);

    /**
     * Removes a hasEmailSHA1Sum property value.<p>
     * 
     * @param oldHasEmailSHA1Sum the hasEmailSHA1Sum property value to be removed.
     */
    void removeHasEmailSHA1Sum(String oldHasEmailSHA1Sum);



    /* ***************************************************
     * Property http://ontology.cybershare.utep.edu/RIM/rim.owl#hasFirstName
     */
     
    /**
     * Gets all property values for the hasFirstName property.<p>
     * 
     * @returns a collection of values for the hasFirstName property.
     */
    Collection<? extends String> getHasFirstName();

    /**
     * Checks if the class has a hasFirstName property value.<p>
     * 
     * @return true if there is a hasFirstName property value.
     */
    boolean hasHasFirstName();

    /**
     * Adds a hasFirstName property value.<p>
     * 
     * @param newHasFirstName the hasFirstName property value to be added
     */
    void addHasFirstName(String newHasFirstName);

    /**
     * Removes a hasFirstName property value.<p>
     * 
     * @param oldHasFirstName the hasFirstName property value to be removed.
     */
    void removeHasFirstName(String oldHasFirstName);



    /* ***************************************************
     * Property http://ontology.cybershare.utep.edu/RIM/rim.owl#hasLastName
     */
     
    /**
     * Gets all property values for the hasLastName property.<p>
     * 
     * @returns a collection of values for the hasLastName property.
     */
    Collection<? extends String> getHasLastName();

    /**
     * Checks if the class has a hasLastName property value.<p>
     * 
     * @return true if there is a hasLastName property value.
     */
    boolean hasHasLastName();

    /**
     * Adds a hasLastName property value.<p>
     * 
     * @param newHasLastName the hasLastName property value to be added
     */
    void addHasLastName(String newHasLastName);

    /**
     * Removes a hasLastName property value.<p>
     * 
     * @param oldHasLastName the hasLastName property value to be removed.
     */
    void removeHasLastName(String oldHasLastName);



    /* ***************************************************
     * Property http://ontology.cybershare.utep.edu/RIM/rim.owl#hasPersonalHomePage
     */
     
    /**
     * Gets all property values for the hasPersonalHomePage property.<p>
     * 
     * @returns a collection of values for the hasPersonalHomePage property.
     */
    Collection<? extends Object> getHasPersonalHomePage();

    /**
     * Checks if the class has a hasPersonalHomePage property value.<p>
     * 
     * @return true if there is a hasPersonalHomePage property value.
     */
    boolean hasHasPersonalHomePage();

    /**
     * Adds a hasPersonalHomePage property value.<p>
     * 
     * @param newHasPersonalHomePage the hasPersonalHomePage property value to be added
     */
    void addHasPersonalHomePage(Object newHasPersonalHomePage);

    /**
     * Removes a hasPersonalHomePage property value.<p>
     * 
     * @param oldHasPersonalHomePage the hasPersonalHomePage property value to be removed.
     */
    void removeHasPersonalHomePage(Object oldHasPersonalHomePage);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
