package edu.utep.cybershare.rim.ontology;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Mon Jun 09 09:34:58 GMT-07:00 2014 by nick
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/RIM/rim.owl#Agency
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AGENCY.<p>
     * 
     */
    public static final OWLClass CLASS_AGENCY = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#Agency"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/RIM/rim.owl#Institution
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class INSTITUTION.<p>
     * 
     */
    public static final OWLClass CLASS_INSTITUTION = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#Institution"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/RIM/rim.owl#Person
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PERSON.<p>
     * 
     */
    public static final OWLClass CLASS_PERSON = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#Person"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/RIM/rim.owl#Project
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROJECT.<p>
     * 
     */
    public static final OWLClass CLASS_PROJECT = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#Project"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/RIM/rim.owl#Resource
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RESOURCE.<p>
     * 
     */
    public static final OWLClass CLASS_RESOURCE = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#Resource"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/RIM/rim.owl#affiliatedWithInstitution
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property AFFILIATEDWITHINSTITUTION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_AFFILIATEDWITHINSTITUTION = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#affiliatedWithInstitution"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/RIM/rim.owl#fundedByAgency
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property FUNDEDBYAGENCY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_FUNDEDBYAGENCY = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#fundedByAgency"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/RIM/rim.owl#fundsProject
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property FUNDSPROJECT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_FUNDSPROJECT = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#fundsProject"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/RIM/rim.owl#hostedByInstitution
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HOSTEDBYINSTITUTION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HOSTEDBYINSTITUTION = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#hostedByInstitution"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/RIM/rim.owl#investigatedByCoPI
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INVESTIGATEDBYCOPI.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INVESTIGATEDBYCOPI = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#investigatedByCoPI"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/RIM/rim.owl#investigatedByPI
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INVESTIGATEDBYPI.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INVESTIGATEDBYPI = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#investigatedByPI"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/RIM/rim.owl#relatedToResource
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property RELATEDTORESOURCE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_RELATEDTORESOURCE = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#relatedToResource"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#topObjectProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TOPOBJECTPROPERTY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TOPOBJECTPROPERTY = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#topObjectProperty"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/RIM/rim.owl#describedByAbstract
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DESCRIBEDBYABSTRACT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DESCRIBEDBYABSTRACT = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#describedByAbstract"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/RIM/rim.owl#endedAtDate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ENDEDATDATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ENDEDATDATE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#endedAtDate"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/RIM/rim.owl#hasAddress
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASADDRESS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASADDRESS = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#hasAddress"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/RIM/rim.owl#hasCity
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASCITY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASCITY = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#hasCity"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/RIM/rim.owl#hasDocumentation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASDOCUMENTATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASDOCUMENTATION = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#hasDocumentation"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/RIM/rim.owl#hasEmailSHA1Sum
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASEMAILSHA1SUM.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASEMAILSHA1SUM = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#hasEmailSHA1Sum"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/RIM/rim.owl#hasFirstName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASFIRSTNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASFIRSTNAME = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#hasFirstName"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/RIM/rim.owl#hasInstitutionHomePage
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASINSTITUTIONHOMEPAGE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASINSTITUTIONHOMEPAGE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#hasInstitutionHomePage"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/RIM/rim.owl#hasInstitutionName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASINSTITUTIONNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASINSTITUTIONNAME = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#hasInstitutionName"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/RIM/rim.owl#hasLastName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLASTNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLASTNAME = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#hasLastName"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/RIM/rim.owl#hasLatitude
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLATITUDE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLATITUDE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#hasLatitude"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/RIM/rim.owl#hasLongitude
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLONGITUDE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLONGITUDE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#hasLongitude"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/RIM/rim.owl#hasPersonalHomePage
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASPERSONALHOMEPAGE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASPERSONALHOMEPAGE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#hasPersonalHomePage"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/RIM/rim.owl#hasProjectHomePage
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASPROJECTHOMEPAGE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASPROJECTHOMEPAGE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#hasProjectHomePage"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/RIM/rim.owl#hasState
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASSTATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASSTATE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#hasState"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/RIM/rim.owl#hasZipCode
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASZIPCODE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASZIPCODE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#hasZipCode"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/RIM/rim.owl#identifiedByCollectionID
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property IDENTIFIEDBYCOLLECTIONID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_IDENTIFIEDBYCOLLECTIONID = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#identifiedByCollectionID"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/RIM/rim.owl#identifiedByGrantID
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property IDENTIFIEDBYGRANTID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_IDENTIFIEDBYGRANTID = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#identifiedByGrantID"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/RIM/rim.owl#identifiedByTitle
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property IDENTIFIEDBYTITLE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_IDENTIFIEDBYTITLE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#identifiedByTitle"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/RIM/rim.owl#startedAtDate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property STARTEDATDATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_STARTEDATDATE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#startedAtDate"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/RIM/rim.owl#wasAwardedAmount
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property WASAWARDEDAMOUNT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_WASAWARDEDAMOUNT = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/RIM/rim.owl#wasAwardedAmount"));


}
