package edu.utep.cybershare.rim.ontology.impl;

import edu.utep.cybershare.rim.ontology.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultPerson <br>
 * @version generated on Fri Jun 13 12:09:56 GMT-07:00 2014 by nick
 */
public class DefaultPerson extends WrappedIndividualImpl implements Person {

    public DefaultPerson(OWLOntology ontology, IRI iri) {
        super(ontology, iri);
    }





    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/RIM/rim.owl#affiliatedWithInstitution
     */
     
    public Collection<? extends Institution> getAffiliatedWithInstitution() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_AFFILIATEDWITHINSTITUTION,
                                               DefaultInstitution.class);
    }

    public boolean hasAffiliatedWithInstitution() {
	   return !getAffiliatedWithInstitution().isEmpty();
    }

    public void addAffiliatedWithInstitution(Institution newAffiliatedWithInstitution) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_AFFILIATEDWITHINSTITUTION,
                                       newAffiliatedWithInstitution);
    }

    public void removeAffiliatedWithInstitution(Institution oldAffiliatedWithInstitution) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_AFFILIATEDWITHINSTITUTION,
                                          oldAffiliatedWithInstitution);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/RIM/rim.owl#hasEmailSHA1Sum
     */
     
    public Collection<? extends String> getHasEmailSHA1Sum() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASEMAILSHA1SUM, String.class);
    }

    public boolean hasHasEmailSHA1Sum() {
		return !getHasEmailSHA1Sum().isEmpty();
    }

    public void addHasEmailSHA1Sum(String newHasEmailSHA1Sum) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASEMAILSHA1SUM, newHasEmailSHA1Sum);
    }

    public void removeHasEmailSHA1Sum(String oldHasEmailSHA1Sum) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASEMAILSHA1SUM, oldHasEmailSHA1Sum);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/RIM/rim.owl#hasFirstName
     */
     
    public Collection<? extends String> getHasFirstName() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASFIRSTNAME, String.class);
    }

    public boolean hasHasFirstName() {
		return !getHasFirstName().isEmpty();
    }

    public void addHasFirstName(String newHasFirstName) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASFIRSTNAME, newHasFirstName);
    }

    public void removeHasFirstName(String oldHasFirstName) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASFIRSTNAME, oldHasFirstName);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/RIM/rim.owl#hasLastName
     */
     
    public Collection<? extends String> getHasLastName() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLASTNAME, String.class);
    }

    public boolean hasHasLastName() {
		return !getHasLastName().isEmpty();
    }

    public void addHasLastName(String newHasLastName) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLASTNAME, newHasLastName);
    }

    public void removeHasLastName(String oldHasLastName) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLASTNAME, oldHasLastName);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/RIM/rim.owl#hasPersonalHomePage
     */
     
    public Collection<? extends Object> getHasPersonalHomePage() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASPERSONALHOMEPAGE, Object.class);
    }

    public boolean hasHasPersonalHomePage() {
		return !getHasPersonalHomePage().isEmpty();
    }

    public void addHasPersonalHomePage(Object newHasPersonalHomePage) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASPERSONALHOMEPAGE, newHasPersonalHomePage);
    }

    public void removeHasPersonalHomePage(Object oldHasPersonalHomePage) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASPERSONALHOMEPAGE, oldHasPersonalHomePage);
    }


}
