package edu.utep.cybershare.rim.ontology.impl;

import edu.utep.cybershare.rim.ontology.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultAgency <br>
 * @version generated on Fri Jun 13 12:09:56 GMT-07:00 2014 by nick
 */
public class DefaultAgency extends WrappedIndividualImpl implements Agency {

    public DefaultAgency(OWLOntology ontology, IRI iri) {
        super(ontology, iri);
    }





    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/RIM/rim.owl#fundsProject
     */
     
    public Collection<? extends Project> getFundsProject() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_FUNDSPROJECT,
                                               DefaultProject.class);
    }

    public boolean hasFundsProject() {
	   return !getFundsProject().isEmpty();
    }

    public void addFundsProject(Project newFundsProject) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_FUNDSPROJECT,
                                       newFundsProject);
    }

    public void removeFundsProject(Project oldFundsProject) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_FUNDSPROJECT,
                                          oldFundsProject);
    }


}
